name: Healthcheck pipeline

on:
  schedule:
    - cron: '00 14 * * *'

jobs:
  health_check:
    steps:
      - name: Health check
        uses: jtalk/url-health-check-action@v4
        with:
          # Tarkistetaan pokedex url
          url: https://full-stack-open-pokedex-snkr.onrender.com
  health_check_notify_FALSE:
    needs: [health_check]
    if: ${{ health_check.result != 'failure'  }}
    steps:
      - name: Health check was success
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          username: tailsUp
          details: Health check has FAILED!.
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
  health_check_notify_OK:
    needs: [health_check]
    if: ${{ health_check.result != 'success'  }}
    steps:
      - name: Health check was success
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          username: tailsUp
          color: '#008000'
          details: Health check has succeeded.
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
