name: Healthcheck pipeline

on:
  schedule:
    - cron: '15 21 * * *'

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Health check
        uses: jtalk/url-health-check-action@v4
        with:
          # Tarkistetaan pokedex url
          url: https://full-stack-open-pokedex-snkr.onrender.com
      - name: Health check
        uses: jtalk/url-health-check-action@v4
        with:
          # Tarkistetaan BLOG_url
          url: https://cicd-repo.onrender.com/
      - name: Notify success
        uses: stegzilla/discord-notify@v4
        if: success()
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          title: Health check OK!
          message: 'Scheduled check has reached pokedex.'
      - name: Notify failure
        uses: stegzilla/discord-notify@v4
        if: failure()
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          title: Health check FAIL!
          message: 'Scheduled check has not reached pokedex.'
  
  
  
  #health_check_notify_FALSE:
  #  needs: [health_check]
  #  if: ${{ health_check.result != 'failure'  }}
  #  steps:
  #    - name: Health check was success
  #      uses: discord-actions/message@v2
  #      with:
  #        webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
  #        message: "Scheduled check has reached webpage."
  #health_check_notify_OK:
  #  needs: [health_check]
  #  if: ${{ health_check.result != 'success'  }}
  #  steps:
  #    - name: Health check was success
  #      uses: discord-actions/message@v2
  #      with:
  #        webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
  #        message: "Scheduled check has noticed that webpage cant be reached."

  #health_check_notify_FALSE:
  #  needs: [health_check]
  #  if: ${{ health_check.result != 'failure'  }}
  #  steps:
  #    - name: Health check was success
  #      uses: rjstone/discord-webhook-notify@v1
  #      with:
  #        severity: error
  #        username: tailsUp
  #        details: Health check has FAILED!.
  #        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
  #health_check_notify_OK:
  #  needs: [health_check]
  #  if: ${{ health_check.result != 'success'  }}
  #  steps:
  #    - name: Health check was success
  #      uses: rjstone/discord-webhook-notify@v1
  #      with:
  #        severity: info
  #        username: tailsUp
  #        color: '#008000'
  #        details: Health check has succeeded.
  #        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}